[tool.poetry]
name = "rv_helper"
version = "0.1.0"
description = "A helper package for rapid visualization"
authors = ["Morris Chan"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
matplotlib = "^3.6.3"
seaborn = "^0.12.2"
scipy = "^1.10.0"
tabulate = "^0.9.0"
pandas = "^1.5.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
